In [2]:
import os 
import pandas as pd
from config import key_dict

In [3]:
census_key = key_dict['census']

In [9]:
data_path= "Resources/deaths.csv"

In [10]:
data_df = pd.read_csv(data_path)

In [11]:
data_df.head()

,Data as of,Start Date,End Date,State,Age group,Race and Hispanic Origin Group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths",Footnote
0,03/17/2021,01/01/2020,03/13/2021,United States,All Ages,Total Deaths,"517,651","3,967,901","445,769","251,252","8,982","719,917",NaN
1,03/17/2021,01/01/2020,03/13/2021,United States,All Ages,Non-Hispanic White,"316,019","2,909,394","288,896","143,602","6,004","466,928",NaN
2,03/17/2021,01/01/2020,03/13/2021,United States,Under 1 year,Non-Hispanic White,12,"8,676",94,1,10,115,NaN
3,03/17/2021,01/01/2020,03/13/2021,United States,0-17 years,Non-Hispanic White,63,"16,030",277,13,84,411,NaN
4,03/17/2021,01/01/2020,03/13/2021,United States,1-4 years,Non-Hispanic White,10,"1,713",59,2,25,92,NaN